---
# tasks file for deploy
- name: update apt
  apt:
   update_cache: yes

- name: build artifacts
  apt: name={{ item }} state=present
  with_items:
    - default-jdk
    - tomcat9

- name: copy war
  synchronize:
   src: {{ synch_src }}
   dest: {{ synch_dest }}
  notify: start tomcat
